# Correlation analysis

Correlation analysis involves measuring relationships between two **continuous** variables. A correlation coefficient indicates the direction of relationship on a scale -1 ... 1 where 0 means lack of relationship. 

See @navarro_learning_2018 section 12.1.

## Scatterplot

Scatterplots illustrate where observations are positioned relative to two continuous variables. This allows us to see if and how two variables are related. Conventionally dependent variables are presented on vertical (y) axis and independent variable on horizontal (x) axis. 

See @navarro_learning_2018 section 12.2.

In Jamovi: `Exploration > Scatterplot`.  
In R: `plot(x, y)`

## Pearson’s correlation coefficient

Evaluates **linear** relationship. Thus, perfect positive correlation implies that when $x$ increases by 1 unit, $y$ also increases by 1 unit.

$$r = \frac{\sum_{i=1}^{n}(x_i-\bar{x})(y_i-\bar{y})}{\sum_{i=1}^{n}(x_i-\bar{x})^2 \sum_{i=1}^{n}(y_i-\bar{y})^2}$$

Essentially, we compare differences from mean value for values of each group.

Statistical significance can also be estimated by finding the probability of t-statistic on t-distribution.

$$t=r\sqrt{n-2}/\sqrt{1-r^{2}}$$

See @navarro_learning_2018 section 12.1.3.

In Jamovi: `Regression > Correlation Matrix > Correlation Coefficients | Pearson`.  
In R: `cor(x)`

## Spearman rank-order correlation coefficient

Evaluation is based on the ranking of values. Evaluates a **monotonic** relationship. Thus perfect positive correlation implies that when $x$ increases, then $y$ also always increases.

$$r = 1 - \frac{6\sum (x_{i}-y_{i})^{2}}{n(n^{2}-1)}$$

Simply put, we compare rankings of values from each group.

See @navarro_learning_2018 section 12.1.6.

In Jamovi: `Regression > Correlation Matrix > Correlation Coefficients | Spearman`.  
In R: `cor(x, method = 'spearman')`

## Correlation matrix and heatmap

To find relationships among large number of variables, correlation coefficients can be summarized as a correlation matrix. 

In Jamovi: `Regression > Correlation Matrix > Plot | Correlation matrix`   
​	or `Factor > Reliability Analysis > Additional Options | Correlation heatmap`.  
In R: `heatmap(cor(x))`

## Causality

It's important to understand that correlation itself does not imply how the causality between variables functions.