---
title: "Research methods"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    config:
      toc:
        collapse: section
      sharing:
        facebook: false
        twitter: false
documentclass: book
bibliography: library.bib
biblio-style: apalike
link-citations: yes
github-repo: lillemets/researchmethods
description: "Research methods course materials"
---

# Syllabus

These course notes include information and study materials on the quantitative part of MS.0825 Research methods course of [Agri-Food Business Management](https://www.emu.ee/en/admissions/agri-food-business-management/) Master's program. 

## Teaching

Flipped classroom approach is used for teaching. This means that students are expected to learn the methods before meetings. During the meetings we revise the theoretical material, address any questions and apply methods in practice. After meetings students apply the methods on their own datasets.

### Schedule

Meetings take place on Mondays, Wednesdays and Thursdays at 9 o'clock in the morning. Link to meetings is provided under the course page in [Moodle](https://moodle.edu.ee).

### Aims

After completing the course students should be able to ...

... understand basic concepts in statistics;  
... know how to describe data, both numerically and visually;   
... choose an appropriate method to solve a problem;  
... use a statistical package for data analysis;  
... communicate results (interpret, explain, present);  
... learn about statistical methods individually;   
... find the courage to apply statistical methods.

## Scoring

This part of the course gives 50% of total course points. This 50% consists of 50 points that can be obtained by submitting:

- feedback on reading material for upcoming meeting (`10*1=10` points), and
- report containing the application of methods learned  (`10*4=40` points).

To gain the 40 points students are required to combine the applications of a method into a report. Participation in meetings does not affect points but meetings are not recorded.

### Feedback on reading material

Submit your questions or thoughts on given reading material before each meeting in [Moodle](https://moodle.edu.ee). Feedback can be either 

- an explanation of something you learned, 
- a question on something you don't understand, or
- an answer to another student's question.

Compulsory reading is from two books: @navarro_learning_2018 and @crawley_r_2013.

Each part of feedback is graded as follows:

- 0 points - Feedback is missing or lacking
- 1 point - Feedback demonstrates that student has revised relevant material

### Research project

Students are required to create a research report as follows:

1. Choose at least one data set
2. Apply at least one method from 10 topics on this data set (i.e. you can skip 2 topics)
3. Make changes according to feedback
4. Present the results as a written report

Each of the 10 topics is graded as follows:

- 0 points - Method from a particular topic is not applied
- 1 point - Method is applied but does not suit data
- 2 points - Chosen method suits data but is incorrectly applied
- 3 points - Method is correctly applied but conclusions are incorrect or missing
- 4 points - Method is correctly applied and conclusions are correct

#### Datasets

To apply methods, datasets need to have multiple variables. We mostly learn to explore continuous data but some methods require at least one discrete variable. Students are free to choose a dataset. Possible sources for data:

- Jamovi: `Open > Data Library`
- [Goodle dataset search](https://datasetsearch.research.google.com/)
- [Kaggle datasets](https://www.kaggle.com/datasets)
- [Data hub collections](https://datahub.io/collections)
- [Our World in Data](https://ourworldindata.org/)
- [World Values Survey](https://www.worldvaluessurvey.org/)
- [European Social Survey](https://www.europeansocialsurvey.org/data/)

## Topics

We cover some common and traditional statistical methods.

1. Descriptive statistics
2. Hypothesis testing. Comparing categorical variables
3. Comparing numerical variables
4. Analysis of variance
5. Correlation analysis
6. Regression. Simple linear regression
7. Regression. Multiple linear regression, factor variables and transformations
8. Regression. Maximum likelihood and binary models
9. Principal component analysis
10. Factor analysis
11. Hierarchical clustering
12. K-means clustering