# Data sets

These data sets are used for practical application of methods. See the info for details on what the variables in data sets represent.

- [barley](../data/barley.csv) - Yield data from a Minnesota barley trial ([info](https://vincentarelbundock.github.io/Rdatasets/doc/lattice/barley.html))
- [chickwts](../data/chickwts.csv) - Chicken Weights by Feed Type ([info](https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/chickwts.html))
- [Cigarettes](../data/Cigarettes.csv) - The Cigarette Consumption Panel Data Set ([info](https://vincentarelbundock.github.io/Rdatasets/doc/Ecdat/Cigarette.html))
- [Computers](../data/Computers.csv) - Prices of Personal Computers ([info](https://vincentarelbundock.github.io/Rdatasets/doc/Ecdat/Computers.html))
- [Crime](../data/Crime.csv) - Crime in North Carolina ([info](https://vincentarelbundock.github.io/Rdatasets/doc/Ecdat/Crime.html))
- [Fatalities](../data/Fatalities.csv) - US Traffic Fatalities ([info](https://vincentarelbundock.github.io/Rdatasets/doc/AER/Fatalities.html))
- [Griliches](../data/Griliches.csv) -  Wage Data ([info](https://vincentarelbundock.github.io/Rdatasets/doc/Ecdat/Griliches.html))
- [gss_spending](../data/gss_spending.csv) - Attitudes Toward National Spending in the General Social Survey (2018) ([info](https://vincentarelbundock.github.io/Rdatasets/doc/stevedata/gss_spending.html))
- [HousePrices](../data/HousePrices.csv) - House Prices in the City of Windsor, Canada ([info](https://vincentarelbundock.github.io/Rdatasets/doc/AER/HousePrices.html))
- [M&Ms](../data/mm.csv) - Color counts and net weight for a sample of 30 bags of M&M's ([info](https://www.randomservices.org/random/data/MM.html))
- [mtcars](../data/mtcars.csv) - Motor Trend Car Road Tests ([info](https://vincentarelbundock.github.io/Rdatasets/doc/datasets/mtcars.html))
- [PhDPublications](../data/PhDPublications.csv) - Doctoral Publications ([info](https://vincentarelbundock.github.io/Rdatasets/doc/AER/PhDPublications.html))
- [PSID1976](../data/PSID1976.csv) -  Labor Force Participation Data ([info](https://vincentarelbundock.github.io/Rdatasets/doc/AER/PSID1976.html))
- [Star](../data/Star.csv) -  Effects on Learning of Small Class Sizes ([info](https://vincentarelbundock.github.io/Rdatasets/doc/Ecdat/Star.html))
- [TeachingRatings](../data/TeachingRatings.csv) -  Impact of Beauty on Instructor's Teaching Ratings ([info](https://vincentarelbundock.github.io/Rdatasets/doc/AER/TeachingRatings.html))
- [UN98](../data/UN98.csv) -  United Nations Social Indicators Data 1998 ([info](https://vincentarelbundock.github.io/Rdatasets/doc/carData/UN98.html))